### ISSUE TITLE
Company Profile - Module is not available

### ISSUE THREAD

**Issue by ATSGithub** [ATSGithub/HRMS#1]
Company Profile - Module is not available
![company profile](https://cloud.githubusercontent.com/assets/24791684/21759081/75791738-d667-11e6-9026-a8ea2f47de27.PNG)

**Comment by PallaviHavale** [comment]
Work by Umashree

**Comment by PallaviHavale** [comment]
Available For Testing

**Comment by ATSGithub** [comment]
Company Profile module is now available. Closed
