### ISSUE TITLE
Designation Settings - Unable to Edit / Delete 

### ISSUE THREAD

**Issue by ATSGithub** [ATSGithub/HRMS#4]
We are unable to Edit / Delete - Designation Settings. 
When we click on any value in the list, a popup is appearing with "Designation ID" and is asking us to delete.
![designation](https://cloud.githubusercontent.com/assets/24791684/21759306/65cc123e-d669-11e6-81a5-da74ffc6ae36.PNG)

**Comment by PallaviHavale** [comment]
Work By Prakash

**Comment by PallaviHavale** [comment]
Available For Testing

**Comment by ATSGithub** [comment]
Working Fine. Closed
