### ISSUE TITLE
Department Settings - Unable to Add Departments 

### ISSUE THREAD

**Issue by ATSGithub** [ATSGithub/HRMS#5]
Department Settings - Unable to Add Departments
We are receiving the error - Portlet is temporarily unavailable.
![department](https://cloud.githubusercontent.com/assets/24791684/21759367/c7c4510e-d669-11e6-9d6a-a88a891d5b7e.PNG)

**Comment by PallaviHavale** [comment]
Work By Pramod

**Comment by PallaviHavale** [comment]
Available For Testing

**Comment by ATSGithub** [comment]
Working Fine.
